### DISCUSSION TITLE
How to set up the docker container?

### DISCUSSION THREAD

**Discussion by sophof** [NickM-27/swatch#70] [General]
I'd like to try this out, but have to run it via docker-compose, since I don't run HA-OS. I found the docker-compose.yaml, but it looks like this needs a working swatch container and isn't meant as an example? what do I need to run this?

I've tried the following:
``` yaml
version: "3"
services:
  swatch:
    container_name: swatch
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - .:/lab/swatch:cached
      - ./config/config.yaml:/config/config.yaml:ro
      - ./debug:/media/
      - ./debug:/database/
    ports:
      - "4500:4500"
      - "4501:4501"
```

but it fails to build all the requirements with the error: 
```
ModuleNotFoundError: No module named 'distutils'

The command '/bin/sh -c pip install -r requirements.txt' returned a non-zero code: 2
ERROR: Service 'dev' failed to build : Build failed
```

I tried adding setuptools to the requirements.txt, but that didn't work.
