### ISSUE TITLE
[Support]: Need help with tuning the color values

### ISSUE THREAD

**Issue by backslashV** [NickM-27/swatch#11]
### Describe the problem you are having

I used a python script to crop the images from my camera with the same coordinates provided in the config file for Swatch. I then uploaded the cropped images to Swatch to get the color values. Below are the results of this test as well as the result of running detect on the original uncropped pictures.

```
midday:
{
    "message": "The dominant color is (151, 36, 46) with a mixed palette as [(156, 39, 49), (183, 168, 169), (203, 139, 150), (85, 6, 13)]",
    "success": true
}

{
    "door": {
        "stop_sign": {
            "area": 81,
            "result": false
        }
    }
}
```
![cropped_midday](https://user-images.githubusercontent.com/8752221/167573855-0b12e59f-f64b-4869-9a29-932279580912.jpg)

```
night_lights_on:
{
    "message": "The dominant color is (64, 22, 26) with a mixed palette as [(62, 14, 18), (79, 74, 74), (130, 84, 90), (84, 60, 68)]",
    "success": true
}

{
    "door": {
        "stop_sign": {
            "area": 99,
            "result": false
        }
    }
}
```
![cropped_night_lights_on_garage](https://user-images.githubusercontent.com/8752221/167573905-a3cb5a57-f2f9-49e7-abc4-08e2fa4bfe4a.jpg)

```
night_spotlight:
{
    "message": "The dominant color is (121, 64, 79) with a mixed palette as [(119, 62, 77), (203, 137, 152), (165, 119, 150), (163, 120, 127)]",
    "success": true
}

{
    "door": {
        "stop_sign": {
            "area": 846,
            "result": false
        }
    }
}
```
![cropped_spotllight_garage](https://user-images.githubusercontent.com/8752221/167573891-f995b709-9802-4ba4-a90b-7bb10e2bd275.jpg)

```
night_door_open:
{
    "message": "The dominant color is (19, 20, 19) with a mixed palette as [(11, 12, 12), (19, 20, 19), (4, 4, 4), (28, 26, 27)]",
    "success": true
}

{
    "door": {
        "stop_sign": {
            "area": 111,
            "result": false
        }
    }
}
```
![cropped_night_door_open_garage](https://user-images.githubusercontent.com/8752221/167574009-7505bce5-8e70-4f34-aff0-b3408351a51a.jpg)

I am not sure what lower and upper color values or min/max pixel thresholds I should use so that the first 3 situations are detected and the last one isn't. Any combination I use either one is incorrectly missed or incorrectly detected. For some reason, even when I had the lower RGB values larger than the values of the 4th situations, Swatch marked it as true. 

### Version

1.0.0

### Swatch config file

```yaml
# REQUIRED: Define a list of objects that are expected to be seen. These can be specific
# to one camera or common between many / all cameras
objects:
  # REQUIRED: Name of the object
  stop_sign:
    # REQUIRED: the lower R, G, B values that are considered a potential match for the object.
    color_lower: 64, 22, 26
    # REQUIRED: the upper R, G, B values that are considered a potential match for the object.
    color_upper: 151, 36, 46
    # OPTIONAL: the min number of pixels with R, G, B values within the bounds to be
    # considered a true positive. This is recommended to be set as a super small amount
    # could be a false positive. (Default: shown below)
    min_area: 1000
    # OPTIONAL: the max number of pixels with R, G, B values within the bounds to be
    # considered a true positive (Default: shown below).
    max_area: 100000

# REQUIRED: Define list of cameras that will be used for color detection.
cameras:
  # REQUIRED: Name of the camera
  garage_cam:
    # REQUIRED: Zones are cropped areas where the object can be expected to be. 
    # This makes searching / matches for efficient and more predictable than searching
    # the entire image.
    zones:
      # REQUIRED: Name of the zone.
      door:
        # REQUIRED: Coordinates to crop the zone by. 
        coordinates: 645, 712, 1368, 1434
        # REQUIRED: List of objects that may be in this zone. These correspond to
        # the objects list defined previously and are matched by name.
        objects:
          - stop_sign
```

### Relevant log output

```shell
N/A
```

**Comment by NickM-27** [comment]
Hi, thanks for this comprehensive issue. There are a few things here:
1. Detect isn't meant to be run on the entire image and just the cropped image, it sounds like the results are from that which is interesting.
2. There is definitely some tuning to be done for some of these cases, but the `night_stoplight` case where the area is 846 seems to be a success unless that is for the entire image. Your `min_area` of 1000 is just too high for that small of an object.

My methodology so far is to use the rgb viewer to see what the dominant color is, set the lower r,g,b to the dominant r * .9,g * .9,b * .9 and the upper r,g,b to r * 1.1,g * 1.1, b * 1.1 and try that.

Thanks for the patience, as I said I intend to get a UI soonish that will make this easier

**Comment by NickM-27** [comment]
Also, the latest version will be changing the config so that it supports multiple color-variants so there aren't multiple objects created for the same "object" in different lighting conditions

**Comment by backslashV** [comment]
Thank you for your response. Regarding #1, should I provide the cropped image to the detect API endpoint? I thought Swatch does the cropping itself. Otherwise, what's the point of providing the coordinates in the config?

**Comment by NickM-27** [comment]
> Thank you for your response. Regarding #1, should I provide the cropped image to the detect API endpoint? I thought Swatch does the cropping itself. Otherwise, what's the point of providing the coordinates in the config?

Yes, that is correct, I think I just misunderstood what you meant above.

**Comment by backslashV** [comment]
Thanks.

**Comment by NickM-27** [comment]
@backslashV You will want to check out latest 2.0 version which includes ui to adjust color values in real time to see what the mask will look like.

**Comment by backslashV** [comment]
Absolutely. Will do it in some time. 👌

**Comment by backslashV** [comment]
Would you be able to update the HA addon with the new config options and the UI editor?

**Comment by NickM-27** [comment]
> Would you be able to update the HA addon with the new config options and the UI editor?

Did it not already get the new version? I'll do that

**Comment by backslashV** [comment]
It seems the new config isn't supported on HA still:
```Starting SwatchApp
Importing SwatchApp Config
Verified SwatchApp Config
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/swatch/swatch/__main__.py", line 14, in <module>
    swatch_app = SwatchApp()
  File "/opt/swatch/swatch/app.py", line 21, in __init__
    self.__init_config__()
  File "/opt/swatch/swatch/app.py", line 35, in __init_config__
    user_config = SwatchConfig.parse_file(config_file)
  File "/opt/swatch/swatch/config.py", line 126, in parse_file
    return cls.parse_obj(config)
  File "/usr/local/lib/python3.10/site-packages/pydantic/main.py", line 511, in parse_obj
    return cls(**obj)
  File "/usr/local/lib/python3.10/site-packages/pydantic/main.py", line 331, in __init__
    raise validation_error
pydantic.error_wrappers.ValidationError: 2 validation errors for SwatchConfig
cameras -> garage_cam -> snapshot_config -> mode
  extra fields not permitted (type=value_error.extra)
cameras -> garage_cam -> snapshot_config -> snapshot_url
  extra fields not permitted (type=value_error.extra)```

**Comment by NickM-27** [comment]
Have you been running in HA OS the whole time? I think there may be more required to get it to work. 

As far as the config goes can you paste the whole thing?

**Comment by backslashV** [comment]
Yes, I'm using HA OS. Here's the config
```
objects:
  stop_sign:
    color_variants:
      midday:
        color_lower: 158, 140, 140
        color_upper: 194, 170, 172
      evening:
        color_lower: 162, 146, 153
        color_upper: 198, 178, 187
      night_lights_on:
        color_lower: 62, 40, 43
        color_upper: 76, 50, 53
      night_spotlight:
        color_lower: 89, 67, 80
        color_upper: 109, 81, 98
    min_area: 55000
    max_area: 190000

cameras:
  garage_cam:
    # auto_detect: 300
    # snapshot_config:
    #   snapshot_url: "<image url here>"
    #   save_detections: false
    #   save_misses: false
    #   mode: "all"
    #   retain_days: 7
    zones:
      door:
        coordinates: 641, 727, 1360, 1440
        objects:
          - stop_sign
```
