### ISSUE TITLE
[Support]: Color Playground

### ISSUE THREAD

**Issue by JmanT-glitch** [NickM-27/swatch#64]
### Describe the problem you are having

Hi, I came across your color detector.
I am trying to get it to read from snapshots stored in /config/www/tmp/snapshot-doorbell.jpg
I have tried both "/config/www/tmp/snapshot-doorbell.jpg" and the url of the image but no image ever pops up on the color playground for me to use. Am I using the wrong link?
Thanks

### Version

Latest

### Swatch config file

```yaml
# REQUIRED: Define a list of objects that are expected to be seen. These can be specific
# to one camera or common between many / all cameras
objects:
  # REQUIRED: Name of the object
  trash_can:
    color_variants:
      default:
        color_lower: 70, 70, 0
        color_upper: 110, 100, 50
        
# REQUIRED: Define list of cameras that will be used for color detection.
cameras:
  # REQUIRED: Name of the camera
  front_doorbell_cam:
    # REQUIRED: Zones are cropped areas where the object can be expected to be.
    # This makes searching / matches for efficient and more predictable than searching
    # the entire image.
    zones:
      # REQUIRED: Name of the zone.
      street:
        # REQUIRED: Coordinates to crop the zone by.
        # NOTE: The order of the coordinates are: x, y, x+w, y+h starting in the top left corner as 0, 0.
        coordinates: 225, 540, 350, 620
        # REQUIRED: List of objects that may be in this zone. These correspond to
        # the objects list defined previously and are matched by name.
        objects:
          - trash_can
```

### Relevant log output

```shell
Dont think I have any
```
