### ISSUE TITLE
[Support]: Bright red bin lid cant be detected

### ISSUE THREAD

**Issue by haroldboom** [NickM-27/swatch#68]
### Describe the problem you are having

Hi all,
I have spent all day trying to get swatch to detect my bright red bin lid. As others have raised I cannot use the color playground so I have been cropping the image and using online/paint color picker to get a range of colors present on the lid however, whatever I do it will never detect the lid. I have tried changing the color ranges looser and looser until it detects the green bin but it will never detect the red. I must be misunderstanding something. I have also change min are to 0 and it just detects random stuff around the bin but never any red. I attached the crop i took of the top to try get the color palette
![Main Scree
![bin](https://github.com/NickM-27/swatch/assets/42967743/22c53f1e-2491-4823-8d9d-f7da6701c30c)
n](https://github.com/NickM-27/swatch/assets/42967743/e7178bea-8881-40a5-9ea9-85862f9b4943)
![Detection](https://github.com/NickM-27/swatch/assets/42967743/6a06e680-f958-440e-8be1-fa52b2a6d3e6)

### Version

3.1.0 HA Addon

### Swatch config file

```yaml
objects:
  garbage_bin:
    color_variants:
      default:
        color_lower: 120, 20, 40
        color_upper: 200, 100, 140
    min_area: 100
    max_area: 3000
cameras:
  front_yard_camera:
    auto_detect: 10
    snapshot_config:
        url: "http://HA:8123/local/snapshots/bin.jpg"
        bounding_box: true
        clean_snapshot: false
        save_detections: true
        save_misses: true
        mode: "all"
        retain_days: 7
    zones:
      front_yard:
        coordinates: 127, 443, 320, 670
        objects:
          - garbage_bin
```

### Relevant log output

```shell
[2024-05-08 16:00:56,415]: INFO - Starting migrations
There is nothing to migrate
[2024-05-08 16:00:56,419]: INFO - There is nothing to migrate
[2024-05-08 16:00:56,420]: INFO - Starting Auto Detection for front_yard_camera
[2024-05-08 16:00:56,420]: INFO - Starting snapshot cleanup
[2024-05-08 16:00:56,420]: INFO - Starting Detection Cleanup
```
